@pva.SuperV.Api_HostAddress = http://localhost:5153
@projectName=TestProject
@baseClassName=BaseClass
@derivedClassName=DerivedClass

# Create a new blank project
POST {{pva.SuperV.Api_HostAddress}}/projects/create
Content-Type: application/json
{
  "name":  "TestProject",
  "description": "A test project",
  "historyStorageConnectionString": null
}
###

# Create field formatter for alarm states
POST {{pva.SuperV.Api_HostAddress}}/field-formatters/{{projectName}}-WIP
Content-Type: application/json
{
    "fieldFormatter":
    {
        "$type": "EnumFormatterModel",
        "name": "AlarmStates",
        "values":
        {
            "-2": "LowLow",
            "-1": "Low",
            "0": "Ok",
            "1": "High",
            "2": "HighHigh"
        }
    }
}

###

# Create a new class without inheritance
POST {{pva.SuperV.Api_HostAddress}}/classes/{{projectName}}-WIP
Content-Type: application/json
{
    "name": "{{baseClassName}}"
}
###

# Create all supported fields in base class
POST {{pva.SuperV.Api_HostAddress}}/fields/{{projectName}}-WIP/{{baseClassName}}
Content-Type: application/json
[
    {
        "$type": "BoolFieldDefinitionModel",
        "name": "BoolField",
        "defaultValue": false
    },
    {
        "$type": "DateTimeFieldDefinitionModel",
        "name": "DateTimeField",
        "defaultValue": "2025-03-05T08:00:00+01:00"
    },
    {
        "$type": "DoubleFieldDefinitionModel",
        "name": "DoubleField",
        "defaultValue": 0.0
    },
    {
        "$type": "FloatFieldDefinitionModel",
        "name": "FloatField",
        "defaultValue": 1.2
    },
    {
        "$type": "IntFieldDefinitionModel",
        "name": "IntField",
        "defaultValue": 0
    },
    {
        "$type": "LongFieldDefinitionModel",
        "name": "LongField",
        "defaultValue": 1
    },
    {
        "$type": "ShortFieldDefinitionModel",
        "name": "ShortField",
        "defaultValue": 2
    },
    {
        "$type": "StringFieldDefinitionModel",
        "name": "StringField",
        "defaultValue": "Hello from SuperV"
    },
    {
        "$type": "TimeSpanFieldDefinitionModel",
        "name": "TimeSpanField",
        "defaultValue": "00:00:00"
    },
    {
        "$type": "UintFieldDefinitionModel",
        "name": "UintField",
        "defaultValue": 3
    },
    {
        "$type": "UlongFieldDefinitionModel",
        "name": "UlongField",
        "defaultValue": 4
    },
    {
        "$type": "UshortFieldDefinitionModel",
        "name": "UshortField",
        "defaultValue": 5
    }
]
###

# Create a new class with inheritance
POST {{pva.SuperV.Api_HostAddress}}/classes/{{projectName}}-WIP
Content-Type: application/json
{
    "name": "{{derivedClassName}}",
    "baseClassName": "{{baseClassName}}"
}
###

# Add fields for alarm state processing
POST {{pva.SuperV.Api_HostAddress}}/fields/{{projectName}}-WIP/{{derivedClassName}}
Content-Type: application/json
[
    {
        "$type": "FloatFieldDefinitionModel",
        "name": "Value",
        "defaultValue": 0
    },
    {
        "$type": "FloatFieldDefinitionModel",
        "name": "HighLimit",
        "defaultValue": 100
    },
        {
        "$type": "FloatFieldDefinitionModel",
        "name": "LowLimit",
        "defaultValue": 0
    },
    {
        "$type": "IntFieldDefinitionModel",
        "name": "AlarmState",
        "defaultValue": 0,
        "valueFormatter": "AlarmStates"
    }
]

###

# Create an alarm state on Value field with only high and low limits and no deadband and acknowldegement fields
POST {{pva.SuperV.Api_HostAddress}}/field-processings/{{projectName}}-WIP/{{derivedClassName}}/Value
Content-Type: application/json
{
    "$type": "AlarmStateProcessingModel",
    "name": "ValueAlarmState",
    "trigerringFieldName": "Value",
    "highLimitFieldName": "HighLimit",
    "lowLimitFieldName": "LowLimit",
    "alarmStateFieldName": "AlarmState"
}
###

# Build project

POST {{pva.SuperV.Api_HostAddress}}/projects/{{projectName}}-WIP/build

###
