# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: dotnet-ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install TDengine driver 
      run: sudo ./TDengine/install-TDengine-client.sh
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal -property:ParallelizeTestCollections=false /property:CollectCoverage=True /property:CoverletOutputFormat=opencover --results-directory ./coverage
    - name: Code Coverage Summary Report
      uses: im-open/code-coverage-report-generator@v5.0.0
      with:
        reports: '*/**/coverage.opencover.xml'
        targetdir: './coverageReport'
        reporttypes: 'Badges;MarkdownSummary'
        assemblyfilters: '-Test*;'
        classfilters: '+*'
        verbosity: 'Warning'
        title: 'pva.SuperV code coverage'
        tag: '${{ github.workflow}}_${{ github.run_id }}'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: ./coverageReport
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: ./codeCoverage/Summary.md
    - name: List files in codecoverage
      run: ls ./codeCoverage